#!/bin/bash

QWERT_SCRIPT_NAME=$1
[ -z "$QWERT_SCRIPT_NAME" ] && {
  echo "Error: You need to pass a parameter (e.g. init or end)"
  exit 1
}

export QWERT_DIR=$HOME/.qwert
QWERT_CONFIG_DIR=$HOME/.config/qwert
QWERT_CUSTOM_ZSH_FILE=$HOME/.config/qwert/zsh/${QWERT_SCRIPT_NAME}.sh

# Add qwert to PATH
#
# if in $PATH, remove, regardless of if it is in the right place (at the front) or not.
# replace all occurrences - ${parameter//pattern/string}
QWERT_BIN="${QWERT_DIR}/bin"
[[ ":$PATH:" == *":${QWERT_BIN}:"* ]] && PATH="${PATH//$QWERT_BIN:/}"

# add to front of $PATH
PATH="${QWERT_BIN}:$PATH"

[ -f $QWERT_CUSTOM_ZSH_FILE ] && {
  [ "$QWERT_VERBOSE" = "1" ] && echo "Sourcing custom zsh file: $QWERT_CUSTOM_ZSH_FILE"
  . $QWERT_CUSTOM_ZSH_FILE
}

unset QWERT_CONFIG_DIR QWERT_CUSTOM_ZSH_FILE QWERT_BIN QWERT_SCRIPT_NAME
