dest = "~/.qwert/iterm2"
macos = [
  "defaults write com.googlecode.iterm2 PrefsCustomFolder -string ~/.qwert/iterm2",
  "defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true",
]

[undo]
macos = [
  "defaults delete com.googlecode.iterm2 PrefsCustomFolder",
  "defaults delete com.googlecode.iterm2 LoadPrefsFromCustomFolder",
]
