[meta]
name = "powerlevel10k"
version = "1.0.0"
description = "Zsh theme with instant prompt and detailed git information"
type = "brew"
pkg = "romkatv/powerlevel10k/powerlevel10k"
depends = ["ohmyzsh"]

[check]
command = "p10k"
version_flag = "version"
